FROM python:3.10-slim
WORKDIR /app
RUN pip install mlflow==2.13.0
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow-artifacts", "--host", "0.0.0.0", "--port", "5000"]